//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSISTANT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASSISTANT()
        {
            this.BACKUP_DATA = new HashSet<BACKUP_DATA>();
            this.TRANSACTIONs = new HashSet<TRANSACTION>();
        }
    
        public string Assistant_ID { get; set; }
        public string Assistant_Name { get; set; }
        public string Assistant_LastName { get; set; }
        public string Assistant_RSA_ID { get; set; }
        public string Assistant_Email { get; set; }
        public string Assistant_PhoneNumber { get; set; }
        public System.DateTime Assistant_Date_Appointed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BACKUP_DATA> BACKUP_DATA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACTION> TRANSACTIONs { get; set; }
    }
}
